[tool.poetry]
name = "cogniq"
version = "0.1.0"
description = ""
authors = ["Jim Park <jim@ramtank.com>"]
license = "All Rights Reserved."
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
slack-bolt = "^1.18.0"
openai = "^0.27.5"
aiohttp = "^3.8.4"
weaviate-client = "^3.16.2"
datasets = "^2.12.0"
apache-beam = "^2.46.0"


[tool.poetry.group.dev.dependencies]
black = "^23.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
