name: _auto_lint

on:
  workflow_call:

# Permissions can only be downgraded by the called workflow.
# Make sure that the calling workflow has at least the following permissions.
permissions:
  contents: write # This is needed to commit changes

jobs:
  black:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - uses: psf/black@stable
        with:
          options: "--verbose"
          src: "."
          jupyter: false
          version: "~=23.3"

      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: "refactor: black :robot: [skip ci]"
