name: _build

on:
  workflow_call:

# Permissions can only be downgraded by the called workflow.
# Make sure that the calling workflow has at least the following permissions.
permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set outputs
      id: vars
      run: |
        # Extract branch or tag from GitHub ref, and remove 'v' prefix for tags
        IMAGE_TAG=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,' -e '/^refs\/tags\//s/^v//')
        echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

        echo "short_sha=$(git rev-parse --short=8 HEAD)" >> $GITHUB_OUTPUT
        echo "timestamp"=$(date --iso-8601=seconds) >> $GITHUB_OUTPUT

        echo "short_commit_message=$(git show --no-patch --format=%s)" >> $GITHUB_OUTPUT
        echo "author_email=$(git show --no-patch --format=%ae)" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

    - name: Build and push
      uses: docker/build-push-action@v4
      id: build
      with:
        push: true
        tags: |
          ghcr.io/cogniq/cogniq:${{ steps.vars.outputs.image_tag }}
          ghcr.io/cogniq/cogniq:${{ steps.vars.outputs.short_sha }}
        cache-from: type=registry,ref=ghcr.io/cogniq/cogniq:buildcache
        cache-to: type=registry,ref=ghcr.io/cogniq/cogniq:buildcache,mode=max,compression=zstd,compression-level=2,ignore-error=true
        build-args: |
          BUILD_TIME=${{ steps.vars.outputs.timestamp }}}
          BUILD_VERSION=${{ steps.vars.outputs.image_tag }}
          BUILD_SHA=${{ steps.vars.outputs.short_sha }}
        labels: |
          org.opencontainers.image.url=${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}
