name: _build

on:
  workflow_call:

# Permissions can only be downgraded by the called workflow.
# Make sure that the calling workflow has at least the following permissions.
permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set outputs
      id: vars
      run: |
        # Extract branch or tag from GitHub ref, and remove 'v' prefix for tags
        IMAGE_TAG=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,' -e '/^refs\/tags\//s/^v//')
        echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

        echo "short_sha=$(git rev-parse --short=8 HEAD)" >> $GITHUB_OUTPUT

        echo "short_commit_message=$(git show --no-patch --format=%s)" >> $GITHUB_OUTPUT
        echo "author_email=$(git show --no-patch --format=%ae)" >> $GITHUB_OUTPUT

    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

    - name: Free up disk space for this particularly large build
      uses: jlumbroso/free-disk-space@v1.2.0

    - id: build
      env:
        DOCKER_BUILDKIT: 1
        REPOSITORY: 'ghcr.io/cogniq/cogniq'
      run: |
        docker pull $REPOSITORY:main || true
        docker pull $REPOSITORY:${{ steps.vars.outputs.image_tag }} || true

        docker buildx build  \
          --pull \
          --push \
          --cache-from $REPOSITORY:main \
          --cache-from $REPOSITORY:${{ steps.vars.outputs.image_tag }} \
          --build-arg BUILD_TIME=$(TIMESTAMP) \
          --build-arg BUILD_VERSION=${{ steps.vars.outputs.image_tag }} \
          --build-arg BUILD_SHA=${{ steps.vars.outputs.short_sha }} \
          --label "org.opencontainers.image.url=${GITHUB_RUN_ID}" \
          -t $REPOSITORY:${{ steps.vars.outputs.image_tag }} \
          -t $REPOSITORY:${{ steps.vars.outputs.short_sha }} \
          -f Dockerfile \
          .