name: _build

on:
  workflow_call:
    inputs:
      image_tag:
        description: 'The tag to use for the image'
        type: string
        required: false
        default: 'main'
      environment:
        description: 'The environment to deploy to'
        type: string
        required: true
        default: 'cogniq-community-main'

# Permissions can only be downgraded by the called workflow.
# Make sure that the calling workflow has at least the following permissions.
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
      url: ${{ inputs.environment }}.eastus.cloudapp.azure.com
    steps:
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 'Deploy to Azure Container Instances'
      uses: azure/container-apps-deploy-action@v1
      with:
        resourceGroup: ${{ inputs.environment }}
        containerAppEnvironment: cogniq-main
        imageToDeploy: ghcr.io/cogniq/cogniq:${{ inputs.image_tag }}
