name: _deploy

on:
  workflow_call:
    inputs:
      image_tag:
        description: 'The tag of the release'
        type: string
        required: true
      short_sha:
        description: 'The short sha of the git ref'
        type: string
        required: true
      environment:
        description: 'The environment to deploy to'
        type: string
        required: true
        default: 'cogniq-community-main'

# Permissions can only be downgraded by the called workflow.
# Make sure that the calling workflow has at least the following permissions.
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
      url: ${{ inputs.environment }}.eastus.cloudapp.azure.com
    steps:
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 'Deploy to Azure Container Apps'
      uses: azure/container-apps-deploy-action@v1
      with:
        resourceGroup: ${{ inputs.environment }}
        containerAppEnvironment: cogniq-web
        containerAppName: cogniq
        imageToDeploy: ghcr.io/cogniq/cogniq:${{ inputs.short_sha }}
        environmentVariables: |
          DD_VERSION=${{ inputs.image_tag }} \
          APP_URL=https://main.cogniq.info \
          PORT=3000 \
          DD_SERVICE=cogniq \
          DD_ENV=cogniq-community-main \
          DD_LOGS_ENABLED=true \
          DD_TRACE_ENABLED=true \
          DD_REMOTE_CONFIGURATION_ENABLED=false \
          DD_SITE=datadoghq.com \
          DD_API_KEY=secretref:dd-api-key \
          DD_AZURE_SUBSCRIPTION_ID=secretref:dd-azure-subscription-id \
          DD_AZURE_RESOURCE_GROUP=cogniq-community-main \
          SLACK_CLIENT_ID=secretref:slack-client-id \
          SLACK_CLIENT_SECRET=secretref:slack-client-secret \
          SLACK_SIGNING_SECRET=secretref:slack-signing-secret \
          OPENAI_API_KEY=secretref:openai-api-key \
          ANTHROPIC_API_KEY=secretref:anthropic-api-key \
          BING_SUBSCRIPTION_KEY=secretref:bing-subscription-key \
          PERPLEXITY_API_KEY=secretref:perplexity-api-key \
          POSTGRES_HOST=secretref:postgres-host \
          POSTGRES_USER=secretref:postgres-user \
          POSTGRES_PASSWORD=secretref:postgres-password \
          POSTGRES_DB=secretref:postgres-db