name: _build

on:
  workflow_call:
    inputs:
      image_tag:
        description: 'The tag to use for the image'
        type: string
        required: false
        default: 'main'
      environment:
        description: 'The environment to deploy to'
        type: string
        required: true
        default: 'cogniq-community-main'

# Permissions can only be downgraded by the called workflow.
# Make sure that the calling workflow has at least the following permissions.
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
      url: ${{ inputs.environment }}.eastus.cloudapp.azure.com
    steps:
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: ${{ inputs.environment }}
        dns-name-label: ${{ inputs.environment }}
        image: ghcr.io/cogniq/cogniq:${{ inputs.image_tag }}
        name: ${{ inputs.environment }}
        location: 'east us'
        cpu: 1
        memory: 1
        environment-variables: |
          PORT=80
        secure-environment-variables: |
          SLACK_SIGNING_SECRET=${{ secrets.SLACK_SIGNING_SECRET }}
          SLACK_BOT_TOKEN=${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_APP_TOKEN=${{ secrets.SLACK_APP_TOKEN }}
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          BING_SUBSCRIPTION_KEY=${{ secrets.BING_SUBSCRIPTION_KEY }}
          BING_SEARCH_ENDPOINT=https://api.bing.microsoft.com
          ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}
  