name: _deploy

on:
  workflow_call:
    inputs:
      image_tag:
        description: 'The tag of the release'
        type: string
        required: true
      short_sha:
        description: 'The short sha of the git ref'
        type: string
        required: true
      environment:
        description: 'The environment to deploy to'
        type: string
        required: true
        default: 'cogniq-community-main'

# Permissions can only be downgraded by the called workflow.
# Make sure that the calling workflow has at least the following permissions.
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
      url: ${{ inputs.environment }}.eastus.cloudapp.azure.com
    steps:
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 'Deploy to Azure Container Apps'
      uses: azure/container-apps-deploy-action@v1
      with:
        resourceGroup: ${{ inputs.environment }}
        containerAppEnvironment: cogniq-web
        containerAppName: cogniq
        imageToDeploy: ghcr.io/cogniq/cogniq:${{ inputs.short_sha }}
        environmentVariables: |
          DD_VERSION=${{ inputs.image_tag }}
