name: on_push

permissions:
  id-token: write
  contents: write
  packages: write
  issues: write
  pull-requests: write

on:
  push:

jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.vars.outputs.image_tag }}
      short_sha: ${{ steps.vars.outputs.short_sha }}
      short_commit_message: ${{ steps.vars.outputs.short_commit_message }}
      author_email: ${{ steps.vars.outputs.author_email }}
    steps:
    - uses: actions/checkout@v3
    - name: Set outputs
      id: vars
      run: |
        # Extract branch or tag from GitHub ref, and remove 'v' prefix for tags
        IMAGE_TAG=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,' -e '/^refs\/tags\//s/^v//')
        echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

        echo "short_sha=$(git rev-parse --short=8 HEAD)" >> $GITHUB_OUTPUT

        echo "short_commit_message=$(git show --no-patch --format=%s)" >> $GITHUB_OUTPUT
        echo "author_email=$(git show --no-patch --format=%ae)" >> $GITHUB_OUTPUT

  release:
    runs-on: ubuntu-latest
    concurrency: ${{ github.workflow }}
    outputs:
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}
      new_release_channel: ${{ steps.semantic.outputs.new_release_channel }}
    steps:
    - uses: actions/checkout@v3
    - id: semantic
      uses: cycjimmy/semantic-release-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        semantic_version: 19
        extra_plugins: |
          @semantic-release/changelog@6
          @semantic-release/git@10

  build:
    uses: ./.github/workflows/_build.yml
    needs:
      - release
    with:
      force: ${{ needs.release.outputs.new_release_published == 'true' && needs.release.outputs.new_release_channel == null }}
      semver: ${{ needs.release.outputs.new_release_version }}

  deploy-cogniq-community-main:
    if: ${{ needs.release.outputs.new_release_published == 'true' && needs.release.outputs.new_release_channel == null }}
    needs:
      - build
      - vars
      - release
    uses: ./.github/workflows/_deploy.yml
    with:
      image_tag: ${{ needs.vars.outputs.image_tag }}
      environment: cogniq-community-main
    secrets: inherit
